package com.panditya.elements_service_user.Repository.Entity.Models.logic;


public enum TeacherTags{

    VETERAN_EDUCATOR,
    YOUNG_EDUCATOR,
    EXPERIENCED,
    FIRST_YEAR,
    EMERGING_LEADER,
    INSPIRATIONAL,
    TRANSFORMATIONAL,
    MOTIVATIONAL,
    ROLE_MODEL,
    LANGUAGE_MAESTRO,
    SPORTS_MENTOR,
    TECH_SAVVY_EDUCATOR,
    ARTS_ADVOCATE,
    CREATIVE,
    HOLISTIC_EDUCATOR,
    EXPERIENTIAL_LEARNING_ADVOCATE,
    CAREER_COACH,
    CERTIFIED_MASTER_TRAINER 
}